config/routes.rb
Realestateapp::Application.routes.draw do
  devise_for :users
  resources :scomps

  resources :comps

  resources :slistings

  resources :listings

  root "pages#home"
  get "about" => "pages#about"
  get "my_profile" => "pages#my_profile"
  get "search_database" => "pages#search_database"
    get "for_lease" => "pages#for_lease"
    get "lease_comps" => "pages#lease_comps"
    get "for_sale" => "pages#for_sale"
    get "sale_comps" => "pages#sale_comps"
    get "property_directory" => "pages#property_directory"
  get "my_listings" => "pages#my_listings"
  get "current_deals" => "pages#current_deals"
  get "closed_deals" => "pages#closed_deals"
  get "accounts_receivable" => "pages#accounts_receivable"
  get "tenant_rep" => "pages#tenant_rep"
  get "landlord_rep" => "pages#landlord_rep"
  get "bitcasa" => "pages#bitcasa"
  get "gameclosure" => "pages#gameclosure"
  get "startx" => "pages#startx"
  get "ccc" => "pages#ccc"
  get "scc" => "pages#scc"
  get "gatowers" => "pages#gatowers"
  get "recently_closed" => "pages#recently_closed"
  get "upcoming_exp" => "pages#upcoming_exp"
  get "create_invoice" => "pages#create_invoice"
  get "commissions" => "pages#commissions"
  get "local" => "pages#local"
  get "national" => "pages#national"
  get "regional" => "pages#regional"
  get "international" => "pages#international"
  get "dashboard" => "pages#dashboard"
  get "pipeline" => "pages#pipeline"
  get "detail" => "pages#detail"
  get "manager_admin" => "pages#manager_admin"
  get "detail_comp" => "pages#detail_comp"
  get "new_listings" => "pages#new_listings"
  get "new_comps" => "pages#new_comps"
  resources :users

  

end

app/models/comp.rb
class Comp < ActiveRecord::Base
	belongs_to :user
	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
end

app/controllers/comps_controller.rb
class CompsController < ApplicationController
  before_action :set_comp, only: [:show, :edit, :update, :destroy]

  # GET /comps
  # GET /comps.json
  def index
    @search = Comp.search(params[:q])
    @comps = @search.result
  end

  # GET /comps/1
  # GET /comps/1.json
  def show

  end

  # GET /comps/new
  def new
    @comp = Comp.new
  end

  # GET /comps/1/edit
  def edit
  end

  # POST /comps
  # POST /comps.json
  def create
    @comp = Comp.new(comp_params)

    respond_to do |format|
      if @comp.save
        format.html { redirect_to @comp, notice: 'Comp was successfully created.' }
        format.json { render action: 'show', status: :created, location: @comp }
      else
        format.html { render action: 'new' }
        format.json { render json: @comp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comps/1
  # PATCH/PUT /comps/1.json
  def update
    respond_to do |format|
      if @comp.update(comp_params)
        format.html { redirect_to @comp, notice: 'Comp was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @comp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comps/1
  # DELETE /comps/1.json
  def destroy
    @comp.destroy
    respond_to do |format|
      format.html { redirect_to comps_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comp
      @comp = Comp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comp_params
      params.require(:comp).permit(:image, :city, :address, :suite, :size, :start_rate, :effective_rate, :opex, :lease_signed, :lease_start, :lease_expiration, :tenant, :landlord, :procurring_broker, :procurring_agent, :listing_broker, :listing_agent)
    end
end

app/helpers/comps_helper.rb
module CompsHelper
end

app/views/comps/_form.html.erb
<div class="container-fluid">
<div class="row">
  <div class="col-md-10 col-md-offset-2">
        <h2 class="page-header"><p><i class="fa fa-building-o fa-2x fa-fw"></i>New Lease Comp</p>
     </div>
   </div>

<div class="row">
  <div class="col-xs-6 col-md-3 col-md-offset-2">

<%= form_for @comp, html: { multipart: true } do |f| %>
  <% if @comp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comp.errors.count, "error") %> prohibited this comp from being saved:</h2>

      <ul>
      <% @comp.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :suite %><br>
    <%= f.text_field :suite %>
  </div>
  <div class="field">
    <%= f.label :size %><br>
    <%= f.text_field :size %>
  </div>
  <div class="field">
    <%= f.label :start_rate %><br>
    <%= f.text_field :start_rate %>
  </div>
  <div class="field">
    <%= f.label :effective_rate %><br>
    <%= f.text_field :effective_rate %>
  </div>
   </div>
  <div class="col-xs-6 col-md-3">
  <div class="field">
    <%= f.label :opex %><br>
    <%= f.text_field :opex %>
  </div>
  <div class="field">
    <%= f.label :lease_signed %><br>
    <%= f.date_select :lease_signed %>
  </div>
  <div class="field">
    <%= f.label :lease_start %><br>
    <%= f.date_select :lease_start %>
  </div>
  <div class="field">
    <%= f.label :lease_expiration %><br>
    <%= f.date_select :lease_expiration %>
  </div>
  <div class="field">
    <%= f.label :tenant %><br>
    <%= f.text_field :tenant %>
  </div>
  <div class="field">
    <%= f.label :landlord %><br>
    <%= f.text_field :landlord %>
  </div>
   </div>
  <div class="col-xs-6 col-md-3">
  <div class="field">
    <%= f.label :procurring_broker %><br>
    <%= f.text_field :procurring_broker %>
  </div>
  <div class="field">
    <%= f.label :procurring_agent %><br>
    <%= f.text_field :procurring_agent %>
  </div>
  <div class="field">
    <%= f.label :listing_broker %><br>
    <%= f.text_field :listing_broker %>
  </div>
  <div class="field">
    <%= f.label :listing_agent %><br>
    <%= f.text_field :listing_agent %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class ="row top-buffer">
  <div class="actions">
    <%= f.submit %>
  </div>
  </div>
<% end %>
</div>
</div>
</div>

app/views/comps/edit.html.erb
<div class="container-fluid">
      <div class="row">
        <div class="col-md-2 sidebar">
          <div class="row placeholders">
          
          <img src="http://www.ccareynkf.com/FileStore/IMG/Agt_59B4875E12004ED397A4A176FE35AD46.jpg" width="130" height="130" class="img-circle"/>
            <h4>Jason Forcier</h4>
              <span class="text-muted">Cornish & Carey</span>
            </div>
          <%= render 'layouts/navbarside' %>
          </div>
<%= render 'form' %>

<%= link_to 'Show', @comp %> |
<%= link_to 'Back', comps_path %>

app/views/comps/index.html.erb
<div class="container-fluid">
      <div class="row">
        <div class="col-md-2 sidebar">
          <div class="row placeholders">
          <img src="http://www.ccareynkf.com/FileStore/IMG/Agt_59B4875E12004ED397A4A176FE35AD46.jpg" width="130" height="130" class="img-circle"/>
            <h4>Jason Forcier</h4>
              <span class="text-muted">Cornish & Carey</span>
            </div>
          <%= render 'layouts/navbarside' %>
          </div><!--column-->
        </div><!--row-->
      </div><!--container-->
<!-- Sidebar Nav -->
<!-- Dashboard Header -->
<div class="row">
        <div class="col-md-10 col-md-offset-2">
          <h2 class="page-header"><p><i class="fa fa-building-o fa-2x fa-fw"></i>Lease Comps</p>
        </div><!--column-->
      </div><!--row-->
          <div class="row">
        <div class="col-md-10 col-md-offset-2">
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Building Photo</th>
      <th>City</th>
      <th>Address</th>
      <th>Suite</th>
      <th>Size</th>
      <th>Effective Rate</th>
      <th>Lease Start</th>
      <th>Lease Expiration</th>
      <th>Tenant</th>
      <th>Landlord</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @comps.each do |comp| %>
      <tr>
        <td><%= image_tag comp.image.url(:thumb) %></td>
        <td><small><%= comp.city %></small></td>
        <td><small><%= comp.address %></small></td>
        <td><small><%= comp.suite %></small></td>
        <td><small><%= comp.size %></small></td>
        <td><small><%= comp.effective_rate %></small></td>
        <td><small><%= comp.lease_start %></small></td>
        <td><small><%= comp.lease_expiration %></small></td>
        <td><small><%= comp.tenant %></small></td>
        <td><small><%= comp.landlord %></small></td>
        <td><%= link_to detail_comp_path do %>
        <i class="fa fa-building-o fa-lg fa-fw"></i><small>View</small>
        <% end %></td>
        <td><%= link_to edit_comp_path(comp) do %>
          <i class="fa fa-pencil-square-o fa-lg fa-fw"></i><small>Edit</small>
          <% end %>
        </td>
        <td><%= link_to comp, method: :delete, data: { confirm: 'Are you sure?' } do %>
        <i class="fa fa-trash-o fa-lg fa-fw"></i><small>Delete</small>
        <% end %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comp', new_comp_path %>

app/views/comps/new.html.erb
<div class="container-fluid">
      <div class="row">
        <div class="col-md-2 sidebar">
          <div class="row placeholders">
          
          <img src="http://www.ccareynkf.com/FileStore/IMG/Agt_59B4875E12004ED397A4A176FE35AD46.jpg" width="130" height="130" class="img-circle"/>
            <h4>Jason Forcier</h4>
              <span class="text-muted">Cornish & Carey</span>
            </div>
          <%= render 'layouts/navbarside' %>
          </div>

<%= render 'form' %>

<%= link_to 'Back', comps_path %>
</div>
</div>

app/views/comps/show.html.erb
<%= link_to 'Back', comps_path %>


<div class="row">
  <div class="col-md-offset-2 col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading center">
        <%= image_tag @comp.image.url(:medium) %>
      </div>
      <div class="panel-body">

<p>
  <strong>City:</strong>
  <%= @comp.city %>
</p>

<p>
  <strong>Address:</strong>
  <%= @comp.address %>
</p>

<p>
  <strong>Suite:</strong>
  <%= @comp.suite %>
</p>

<p>
  <strong>Size:</strong>
  <%= @comp.size %>
</p>

<p>
  <strong>Start rate:</strong>
  <%= @comp.start_rate %>
</p>

<p>
  <strong>Effective rate:</strong>
  <%= @comp.effective_rate %>
</p>

<p>
  <strong>Opex:</strong>
  <%= @comp.opex %>
</p>

<p>
  <strong>Lease signed:</strong>
  <%= @comp.lease_signed %>
</p>

<p>
  <strong>Lease start:</strong>
  <%= @comp.lease_start %>
</p>

<p>
  <strong>Lease expiration:</strong>
  <%= @comp.lease_expiration %>
</p>

<p>
  <strong>Tenant:</strong>
  <%= @comp.tenant %>
</p>

<p>
  <strong>Landlord:</strong>
  <%= @comp.landlord %>
</p>

<p>
  <strong>Procurring broker:</strong>
  <%= @comp.procurring_broker %>
</p>

<p>
  <strong>Procurring agent:</strong>
  <%= @comp.procurring_agent %>
</p>

<p>
  <strong>Listing broker:</strong>
  <%= @comp.listing_broker %>
</p>

<p>
  <strong>Listing agent:</strong>
  <%= @comp.listing_agent %>
</p>

<% if @comp.user == current_user %>
<%= link_to 'Edit', edit_comp_path(@comp) %> |
<% end %>

        </div>
      </div>
    </div>
  </div>