config/routes.rb
Realestateapp::Application.routes.draw do
  devise_for :users
  resources :scomps

  resources :comps

  resources :slistings

  resources :listings

  root "pages#home"
  get "about" => "pages#about"
  get "my_profile" => "pages#my_profile"
  get "search_database" => "pages#search_database"
    get "for_lease" => "pages#for_lease"
    get "lease_comps" => "pages#lease_comps"
    get "for_sale" => "pages#for_sale"
    get "sale_comps" => "pages#sale_comps"
    get "property_directory" => "pages#property_directory"
  get "my_listings" => "pages#my_listings"
  get "current_deals" => "pages#current_deals"
  get "closed_deals" => "pages#closed_deals"
  get "accounts_receivable" => "pages#accounts_receivable"
  get "tenant_rep" => "pages#tenant_rep"
  get "landlord_rep" => "pages#landlord_rep"
  get "bitcasa" => "pages#bitcasa"
  get "gameclosure" => "pages#gameclosure"
  get "startx" => "pages#startx"
  get "ccc" => "pages#ccc"
  get "scc" => "pages#scc"
  get "gatowers" => "pages#gatowers"
  get "recently_closed" => "pages#recently_closed"
  get "upcoming_exp" => "pages#upcoming_exp"
  get "create_invoice" => "pages#create_invoice"
  get "commissions" => "pages#commissions"
  get "local" => "pages#local"
  get "national" => "pages#national"
  get "regional" => "pages#regional"
  get "international" => "pages#international"
  get "dashboard" => "pages#dashboard"
  get "pipeline" => "pages#pipeline"
  get "detail" => "pages#detail"
  get "manager_admin" => "pages#manager_admin"
  get "detail_comp" => "pages#detail_comp"
  get "new_listings" => "pages#new_listings"
  get "new_comps" => "pages#new_comps"
  resources :users

  

end

app/models/listing.rb
class Listing < ActiveRecord::Base
	belongs_to :user
	has_attached_file :image, :styles => { :large => "1200x1200>", :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /listings
  # GET /listings.json
  def index
    @search = Listing.search(params[:q])
    @listings = @search.result
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
    @listings = Listing.all
  end

  # GET /listings/new
  def new
    @listing = current_user.listings.build
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = current_user.listings.build(listing_params)

      if @listing.save
        redirect_to @listing, notice: 'Listing was succesffuly created.'
      else
        render action: 'new'
      end
    end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
      if @listing.update(listing_params)
        redirect_to @listing, notice: 'Listing was succesffuly updated.'
      else
        render action: 'edit'
      end
    end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    redirect_to listings_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    def correct_user
      @listing = current_user.listings.find_by(id: params[:id])
      redirect_to listings_path, notice: "Not authorized to edit this Listing" if @listing.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:image, :city, :address, :suite, :size, :building_type, :building_class, :asking_rate, :opex, :lease_type, :brokerage, :notes)
    end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<div class="container-fluid">
<div class="row">
  <div class="col-md-10 col-md-offset-2">
        <h2 class="page-header"><p><i class="fa fa-building-o fa-2x fa-fw"></i>New Lease Listing</p>
     </div>
   </div>

<div class="row">
  <div class="col-xs-6 col-md-3 col-md-offset-2">
<%= form_for @listing, html: { multipart: true } do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% @listing.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :suite %><br>
    <%= f.text_field :suite %>
  </div>
  <div class="field">
    <%= f.label :size %><br>
    <%= f.text_field :size %>
  </div>
  <div class="field">
    <%= f.label :building_type %><br>
    <%= f.text_field :building_type %>
  </div>
</div>
  <div class="col-xs-6 col-md-3">
  <div class="field">
    <%= f.label :building_class %><br>
    <%= f.text_field :building_class %>
  </div>
  <div class="field">
    <%= f.label :asking_rate %><br>
    <%= f.text_field :asking_rate %>
  </div>
  <div class="field">
    <%= f.label :opex %><br>
    <%= f.text_field :opex %>
  </div>
  <div class="field">
    <%= f.label :lease_type %><br>
    <%= f.text_field :lease_type %>
  </div>
  <div class="field">
    <%= f.label :brokerage %><br>
    <%= f.text_field :brokerage %>
  </div>
</div>
<div class="col-xs-6 col-md-3">
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </div>
   <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
</div>

</div>
</div>
<% end %>

app/views/listings/edit.html.erb
<div class="container-fluid">
      <div class="row">
        <div class="col-md-2 sidebar">
          <div class="row placeholders">
          
          <img src="http://www.ccareynkf.com/FileStore/IMG/Agt_59B4875E12004ED397A4A176FE35AD46.jpg" width="130" height="130" class="img-circle"/>
            <h4>Jason Forcier</h4>
              <span class="text-muted">Cornish & Carey</span>
            </div>
          <%= render 'layouts/navbarside' %>
          </div>
<%= render 'form' %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<div class="container-fluid">
      <div class="row">
        <div class="col-md-2 sidebar">
          <div class="row placeholders">
          <img src="http://www.ccareynkf.com/FileStore/IMG/Agt_59B4875E12004ED397A4A176FE35AD46.jpg" width="130" height="130" class="img-circle"/>
            <h4>Jason Forcier</h4>
              <span class="text-muted">Cornish & Carey</span>
            </div>
          <%= render 'layouts/navbarside' %>
          </div><!--column-->
        </div><!--row-->
      </div><!--container-->
<!-- Sidebar Nav -->
<!-- Dashboard Header -->
<div class="row">
        <div class="col-md-10 col-md-offset-2">
          <h2 class="page-header"><p><i class="fa fa-building-o fa-2x fa-fw"></i>Available - For Lease</p>
        </div><!--column-->
      </div><!--row-->

<div class="row">
  <div class="col-md-10 col-md-offset-2">

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Building Photo</th>
      <th><%= sort_link @search, :agent, "Agent" %></th>
      <th><%= sort_link @search, :city, "City" %></th>
      <th>Address</th>
      <th>Suite</th>
      <th>Size</th>
      <th>Style</th>
      <th>Class</th>
      <th>Lease Type</th>
      <th><%= sort_link @search, :asking_Rate, "Asking Rate" %></th>
      <th>Opex</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @listings.each do |listing| %>
      <tr>
        <td><%= image_tag listing.image.url(:thumb) %></td>
        <td><small><%= listing.user.name if listing.user %></small></td>
        <td><small><%= listing.city %></small></td>
        <td><small><%= listing.address %></small></td>
        <td><small><%= listing.suite %></small></td>
        <td><small><%= listing.size %></small></td>
        <td><small><%= listing.building_type %></small></td>
        <td><small><%= listing.building_class %></small></td>
        <td><small><%= listing.lease_type %></small></td>
        <td><small><%= listing.asking_rate %></small></td>
        <td><small><%= listing.opex %></small></td>
        <td><%= link_to detail_path do %>
        <i class="fa fa-building-o fa-lg fa-fw"></i><small>View</small>
        <% end %>
      </td>
        <% if listing.user == current_user %>
        <td><%= link_to edit_listing_path(listing) do %>
          <i class="fa fa-pencil-square-o fa-lg fa-fw"></i><small>Edit</small>
          <% end %>
        </td>
        <td><%= link_to listing, method: :delete, data: { confirm: 'Are you sure?' } do %>
        <i class="fa fa-trash-o fa-lg fa-fw"></i><small>Delete</small>
        <% end %>
        <% end %>
      </td>
      </tr>

    <% end %>
  </tbody>
</table>
</div>
</div>

<div class="row">
  <div class="col-md-10 col-md-offset-2">
<% if user_signed_in? %>
<%= link_to 'New Lease Listing', new_listing_path %>
<% end %>
</div>
</div>

app/views/listings/new.html.erb
<div class="container-fluid">
      <div class="row">
        <div class="col-md-2 sidebar">
          <div class="row placeholders">
          
          <img src="http://www.ccareynkf.com/FileStore/IMG/Agt_59B4875E12004ED397A4A176FE35AD46.jpg" width="130" height="130" class="img-circle"/>
            <h4>Jason Forcier</h4>
              <span class="text-muted">Cornish & Carey</span>
            </div>
          <%= render 'layouts/navbarside' %>
          </div>
    

<%= render "form" %>


<%= link_to 'Back', listings_path %>
</div>
</div>

<button type="button" class="btn btn-u btn-u-green">Set Private</button>

app/views/listings/show.html.erb
<%= link_to 'Back', listings_path %>


<div class="row">
  <div class="col-md-offset-1 col-md-10">
    <div class="panel panel-default">
      <div class="panel-heading center">
        <%= image_tag @listing.image.url(:medium)%>
      </div>
      <div class="panel-body">
        <div class="col-md-5">

        <p>
          <strong>City:</strong>
          <%= @listing.city %>
        </p>

        <p>
          <strong>Address:</strong>
          <%= @listing.address %>
        </p>

        <p>
          <strong>Suite #:</strong>
          <%= @listing.suite %>
        </p>

        <p>
          <strong>Size:</strong>
          <%= @listing.size %>
        </p>

        <p>
          <strong> Style:</strong>
          <%= @listing.building_type %>
        </p>
</div>
<div class="col-md-6">
        <p>
          <strong>Class:</strong>
          <%= @listing.building_class %>
        </p>

        <p>
          <strong>Asking Rate:</strong>
          <%= @listing.asking_rate %>
        </p>

        <p>
          <strong>Opex:</strong>
          <%= @listing.opex %>
        </p>

        <p>
          <strong>Lease Type:</strong>
          <%= @listing.lease_type %>
        </p>

        <p>
          <strong>Brokerage:</strong>
          <%= @listing.brokerage %>
        </p>

        <p>
          <strong>Notes:</strong>
          <%= @listing.notes %>
        </p>


<% if @listing.user == current_user %>
<%= link_to 'Edit', edit_listing_path(@listing) %> |
<% end %>

        </div>
      </div>
    </div>
  </div>
</div>