config/routes.rb
Realestateapp::Application.routes.draw do
  devise_for :users
  resources :scomps

  resources :comps

  resources :slistings

  resources :listings

  root "pages#home"
  get "about" => "pages#about"
  get "my_profile" => "pages#my_profile"
  get "search_database" => "pages#search_database"
    get "for_lease" => "pages#for_lease"
    get "lease_comps" => "pages#lease_comps"
    get "for_sale" => "pages#for_sale"
    get "sale_comps" => "pages#sale_comps"
    get "property_directory" => "pages#property_directory"
  get "my_listings" => "pages#my_listings"
  get "current_deals" => "pages#current_deals"
  get "closed_deals" => "pages#closed_deals"
  get "accounts_receivable" => "pages#accounts_receivable"
  get "tenant_rep" => "pages#tenant_rep"
  get "landlord_rep" => "pages#landlord_rep"
  get "bitcasa" => "pages#bitcasa"
  get "gameclosure" => "pages#gameclosure"
  get "startx" => "pages#startx"
  get "ccc" => "pages#ccc"
  get "scc" => "pages#scc"
  get "gatowers" => "pages#gatowers"
  get "recently_closed" => "pages#recently_closed"
  get "upcoming_exp" => "pages#upcoming_exp"
  get "create_invoice" => "pages#create_invoice"
  get "commissions" => "pages#commissions"
  get "local" => "pages#local"
  get "national" => "pages#national"
  get "regional" => "pages#regional"
  get "international" => "pages#international"
  get "dashboard" => "pages#dashboard"
  get "pipeline" => "pages#pipeline"
  get "detail" => "pages#detail"
  get "manager_admin" => "pages#manager_admin"
  get "detail_comp" => "pages#detail_comp"
  get "new_listings" => "pages#new_listings"
  get "new_comps" => "pages#new_comps"
  resources :users

  

end

app/views/pages/about.html.erb
H1> About Us </h1>

	<p>
		We are working on this page!
	</p>

app/views/pages/ccc.html.erb
<div class="container-fluid">
      <div class="row">
        <div class="col-md-2 sidebar">
          <div class="row placeholders">
          <img src="http://www.ccareynkf.com/FileStore/IMG/Agt_59B4875E12004ED397A4A176FE35AD46.jpg" width="130" height="130" class="img-circle"/>
            <h4>Jason Forcier</h4>
              <span class="text-muted">Cornish & Carey</span>
            </div>
          <%= render 'layouts/navbarside' %>
          </div><!--column-->
        </div><!--row-->
      </div><!--container-->
<!-- Sidebar Nav -->
<!-- Dashboard Header -->
<div class="row">
        <div class="col-md-10 col-md-offset-2">
          <h2 class="page-header"><p><i class="fa fa-folder-open fa-2x"></i> Current Deals - Listing</p>
          <div class="btn-group">
            <button type="button" class="btn btn-u btn-u-green">Listings</button>
            <button type="button" class="btn btn-u btn-u-green dropdown-toggle" data-toggle="dropdown">
              <span class="caret"></span>
              <span class="sr-only">Toggle Dropdown</span>
            </button>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "Procuring", current_deals_path %></li>
            </ul>
        </div></h2>
        </div>
      </div>
 <div class="row">
        <div class="col-md-10 col-md-offset-2">
          <ul class="nav nav-tabs">
          <li class="active"><%= link_to 'Cupertino City Center', ccc_path %></li>
          <li><%= link_to 'Santa Clara Office Center', scc_path %></li>
          <li><%= link_to 'Great America Towers', gatowers_path %></li>
          <li><button type="button" class="btn btn-u btn-u-green"><i class="fa fa-plus-square fa-fw"></i>Add Listing</button></li>
          </ul>
        </div><!--column-->
  </div><!--row-->

<div class="row top-buffer">
  <div class="col-md-10 col-md-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Overview</h3>
      </div><!--panelheading-->
      <div class="panel-body">
        <div class="row">
          <div class="col-md-12">
            <button type="button" class="btn btn-u btn-u-green"><i class="fa fa-camera fa-fw"></i>Create Report</button>
        </div>
      </div>
        <div class="row top-buffer">
          <div class="col-md-12">
            <table class="table table-hover">
          <thead>
            <tr>
              <th>Partner (If Any)</th>
              <th>Landlord</th>
              <th>Contact</th>
              <th>Building Size</th>
              <th>Vacancy</th>
              <th>Asking Rate</th>
              <th>Opex</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Phil Mahoney</td>
              <td>Prometheus</td>
              <td>John Moe</td>
              <td>150,000sf</td>
              <td>14%</td>
              <td>$4.00NNN</td>
              <td>$1.25</td>
              <td><i class="fa fa-pencil-square-o fa-lg"></i></td>
              
            </tr>
          </tbody>
        </table>
        </div><!--column-->
          </div><!--row-->
        </div><!--panelbody-->
      </div><!--paneldefault-->
    </div><!--column-->
  </div><!--row-->

<div class="row">
  <div class="col-md-10 col-md-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Pending Deals</h3>
      </div><!--panelheading-->
      <div class="panel-body">
        <div class="row">
          <div class="col-md-12">
            <button type="button" class="btn btn-u btn-u-green"><i class="fa fa-plus-square fa-fw"></i>Add Deal</button>
        </div>
      </div>
        <div class="row top-buffer">
          <div class="col-md-12">
            <table class="table table-hover">
              <thead>
                <tr>
                  <th>Tenant</th>
                  <th>Broker/Agent</th>
                  <th>Suite</th>
                  <th>Size (SF)</th>
                  <th>Deal Stage</th>
                  <th>Comments</th>
                  <th>Documents</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>

                <tr>
                  <td>Micro Electronics, Inc</td>
                  <td>Sean Whitney - Cornish & Carey</td>
                  <td># 350</td>
                  <td>10,000SF</td>
                  <td>Lease out for signature</td>
                  <td>Executed copies expected next monday </td>
                  <td><a href="#">
                      <img src="http://img.docstoccdn.com/thumb/orig/123748539.png" width="50" height="50"/></td>
                      <td><i class="fa fa-pencil-square-o fa-lg"></i></td>
                </tr>
                <tr>
                  <td>Nebula, Inc.</td>
                  <td>Ben Stern - Cornish & Carey</td>
                  <td>#400</td>
                  <td>6,500sf</td>
                  <td>Proposals</td>
                  <td>Sent offer yesterday. Touch base early next week.</td>
                  <td><a href="#">
                      <img src="http://img.docstoccdn.com/thumb/orig/123748539.png" width="50" height="50"/></td>
                      <td><i class="fa fa-pencil-square-o fa-lg"></i></td>
                </tr>
              </tbody>
            </table>
            </div><!--column-->
          </div><!--row-->
        </div><!--panelbody-->
      </div><!--paneldefault-->
    </div><!--column-->
  </div><!--row-->

<div class="row">
  <div class="col-md-10 col-md-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Touring Activity</h3>
      </div><!--panelheading-->
      <div class="panel-body">
        <div class="row">
          <div class="col-md-12">
            <button type="button" class="btn btn-u btn-u-green"><i class="fa fa-plus-square fa-fw"></i>Add Prospect</button>
        </div>
      </div>
        <div class="row top-buffer">
          <div class="col-md-12">
            <table class="table table-hover">
              <thead>
                <tr>
                  <th>Tenant</th>
                  <th>Broker/Agent</th>
                  <th>Requirement</th>
                  <th>Timing</th>
                  <th>Tour (y/n)</th>
                  <th>Tour Date</th>
                  <th>Comments/Notes</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>N/A</td>
                  <td>Jason Forcier - Cornish & Carey </td>
                  <td>4,000-6,000sf, 3 Conf Rooms and 1 Private</td>
                  <td>Q'2 - 2014</td>
                  <td>Yes</td>
                  <td> 1/15/2014 </td>
                  <td>Preliminary Interest</td>
                  <td> <i class="fa fa-pencil-square-o fa-lg"></i><i class="fa fa-trash-o fa-lg"></i></td>
                </tr>
                <tr>
                  <td>ABC, Inc.</td>
                  <td>Mike Connor - CTBT </td>
                  <td>10,000-15,000sf, Law firm buildout</td>
                  <td>Q'4 - 2014</td>
                  <td>Yes</td>
                  <td> 1/24/2014 </td>
                  <td>Liked suite 400. Expecting proposal from Broker soon.</td>
                  <td> <i class="fa fa-pencil-square-o fa-lg"></i><i class="fa fa-trash-o fa-lg"></i></td>
                </tr>
                <tr>
                  <td>XYZ, Inc.</td>
                  <td>Rich Branning - JLL </td>
                  <td>20,000-35,000sf, Tech office layout. Large server room needed</td>
                  <td>Q'2 - 2015</td>
                  <td>No</td>
                  <td> N/A </td>
                  <td>Setting up tour for next week</td>
                  <td> <i class="fa fa-pencil-square-o fa-lg"></i><i class="fa fa-trash-o fa-lg"></i></td>
                </tr>
              </tbody>
            </table>
            </div><!--column-->
          </div><!--row-->
        </div><!--panelbody-->
      </div><!--paneldefault-->
    </div><!--column-->
  </div><!--row-->

app/views/pages/gameclosure.html.erb
<div class="container-fluid">
      <div class="row">
        <div class="col-md-2 sidebar">
          <div class="row placeholders">
          <img src="http://www.ccareynkf.com/FileStore/IMG/Agt_59B4875E12004ED397A4A176FE35AD46.jpg" width="130" height="130" class="img-circle"/>
            <h4>Jason Forcier</h4>
              <span class="text-muted">Cornish & Carey</span>
            </div>
          <%= render 'layouts/navbarside' %>
          </div><!--column-->
        </div><!--row-->
      </div><!--container-->
<!-- Sidebar Nav -->
<!-- Dashboard Header -->
<div class="row">
        <div class="col-md-10 col-md-offset-2">
          <h2 class="page-header"><p><i class="fa fa-folder-open fa-2x"></i> Current Deals - Procuring</p><div class="btn-group">
        <button type="button" class="btn btn-u btn-u-green">Procuring</button>
        <button type="button" class="btn btn-u btn-u-green dropdown-toggle" data-toggle="dropdown">
          <span class="caret"></span>
          <span class="sr-only">Toggle Dropdown</span>
        </button>
        <ul class="dropdown-menu" role="menu">
          <li><%= link_to "Listings", landlord_rep_path %></li>
        </ul>
      </div></h2>
        </div>
      </div>
      <div class="row">
        <div class="col-md-10 col-md-offset-2">
<ul class="nav nav-tabs">
	<li><%= link_to 'Bitcasa', bitcasa_path %></li>
     <li class="active"><%= link_to 'GameClosure', gameclosure_path %></li> 
     <li><%= link_to 'StartX', startx_path %></li>
      <li><button type="button" class="btn btn-u btn-u-green"><i class="fa fa-plus-square fa-fw"></i>Add Client</button></li>
    </ul>
    </div>
  </div>
<div class="row top-buffer">
  <div class="col-md-10 col-md-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Client Overview</h3>
      </div><!--panelheading-->
      <div class="panel-body">
        <div class="row">
          <div class="col-md-12">
            <button type="button" class="btn btn-u btn-u-green"><i class="fa fa-camera fa-fw"></i>Create Report</button>
        </div>
      </div>
        <div class="row top-buffer">
        <div class="col-md-12">
          <table class="table table-hover">
            <thead>
              <tr>
                <th>Partner (If Any)</th>
                <th>Requirement</th>
                <th>Areas of Interest</th>
                <th>Timing</th>
                <th>Contact(s)</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
			<tr>
			<td>Jeff Arrillaga</td>
			<td>5,000 - 10,000sf. Tech space.</td>
			<td>Mountain View</td>
			<td>Q'2 - 2014</td>
			<td>Michael Carter</td>	
      <td><i class="fa fa-pencil-square-o fa-lg"></i></td>
			</tr>
            </tbody>
          </table>
          </div><!--column-->
          </div><!--row-->
        </div><!--panelbody-->
      </div><!--paneldefault-->
    </div><!--column-->
  </div><!--row-->

<div class="row">
  <div class="col-md-10 col-md-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Buildings Toured</h3>
      </div><!--panelheading-->
      <div class="panel-body">
        <div class="row">
          <div class="col-md-12">
            <button type="button" class="btn btn-u btn-u-green"><i class="fa fa-plus-square fa-fw"></i>Add Building</button>
        </div>
      </div>
      <div class="row top-buffer">
        <div class="col-md-12">
    <table class="table table-hover">
  <thead>
    <tr>
      <th>Building Photo</th>
      <th>Address</th>
      <th>Suite</th>
      <th>Size</th>
      <th>Rate</th>
      <th>Comments/Notes</th>
      <th>Brochures/Floorplans</th>
      <th></th>
    </tr>
  </thead>
  <tbody>

    <tr>
      <td><a href="#">
            <img src="http://s.lnimg.com/xnet/mainsite/HttpHandlers/attachment/ServeAttachment.ashx?FileGuid=03516c1a58484c9c8ad4ea33f98459c2&Extension=jpg&Width=0&Height=0" width="100" height="100"/> </td>
      <td>650 Castro Street, Mountain View</td>
      <td>#350</td>
      <td>10,000sf</td>
      <td>$5.00 NNN</td>
      <td>Liked Space, thought layout was funky. In Top 3</td>
      <td><a href="#">
            <img src="http://s.lnimg.com/photo/poster/1a3560c8bcaa45be9dd35d76f85d97fb.jpg" width="50" height="50"/>
            <a href="#">
            <img src="http://www.execsuitescheyenne.com/public/Floorplan_mezz.jpg" width="50" height="50"/></td>
      <td> <i class="fa fa-pencil-square-o fa-lg"></i><i class="fa fa-trash-o fa-lg"></i></td>
    </tr>
    <tr>
      <td><a href="#">
            <img src="http://s.lnimg.com/xnet/mainsite/HttpHandlers/attachment/ServeAttachment.ashx?FileGuid=18bf7fc7dbfb4e3fa49882f0c7bf5da5&Extension=jpg&Width=0&Height=0" width="100" height="100"/></td>
      <td>444 Castro Street, Mountain View</td>
      <td>#600</td>
      <td>9,500sf</td>
      <td>$4.75 NNN</td>
      <td>Favorite Space. Good combination of open office and privates. Drafting Proposal</td>
      <td><a href="#">
            <img src="http://s.lnimg.com/photo/poster/1a3560c8bcaa45be9dd35d76f85d97fb.jpg" width="50" height="50"/>
            <a href="#">
            <img src="http://www.execsuitescheyenne.com/public/Floorplan_mezz.jpg" width="50" height="50"/></td>
      <td> <i class="fa fa-pencil-square-o fa-lg"></i><i class="fa fa-trash-o fa-lg"></i></td>
    </tr>
    <tr>
      <td><a href="#">
            <img src="http://s.lnimg.com/xnet/mainsite/HttpHandlers/attachment/ServeAttachment.ashx?FileGuid=8d1a86a5cdf74a638c8ea32bf668fb90&Extension=jpg&Width=0&Height=0" width="100" height="100"/></td>
      <td>100 Mathilda Place, Sunnyvale</td>
      <td>#200</td>
      <td>11,500sf</td>
      <td>$4.25 NNN</td>
      <td>#2 space. Great layout, alternative location</td>
      <td><a href="#">
            <img src="http://s.lnimg.com/photo/poster/1a3560c8bcaa45be9dd35d76f85d97fb.jpg" width="50" height="50"/>
            <a href="#">
            <img src="http://www.execsuitescheyenne.com/public/Floorplan_mezz.jpg" width="50" height="50"/></td>
      <td> <i class="fa fa-pencil-square-o fa-lg"></i><i class="fa fa-trash-o fa-lg"></i></td>
    </tr>
  </tbody>
</table>
</div><!--column-->
</div><!--row-->
</div><!--panelbody-->
</div><!--paneldefault-->
</div><!--column-->
</div><!--row-->

<div class="row">
  <div class="col-md-10 col-md-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Proposals/Offers</h3>
      </div><!--panelheading-->
      <div class="panel-body">
        <div class="row">
          <div class="col-md-12">
            <button type="button" class="btn btn-u btn-u-green"><i class="fa fa-plus-square fa-fw"></i>Add Proposal</button>
        </div>
      </div>
      <div class="row top-buffer">
        <div class="col-md-12">
          <table class="table table-hover">
            <thead>
              <tr>
                <th>Building Photo </th>
                <th>Address</th>
                <th>Suite </th>
                <th>Size</th>
                <th>Deal Stage</th>
                <th>Comments/Notes</th>
                <th>Documents</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><a href="#">
                      <img src="http://s.lnimg.com/xnet/mainsite/HttpHandlers/attachment/ServeAttachment.ashx?FileGuid=18bf7fc7dbfb4e3fa49882f0c7bf5da5&Extension=jpg&Width=0&Height=0" width="100" height="100"/></td>
                <td>444 Castro Street, Mountain View</td>
                <td>#650</td>
                <td>9,500sf</td>
                <td>Sent Proposal</td>
                <td>Sent proposal today. Awaiting Feedback</td>
                <td><img src="http://img.docstoccdn.com/thumb/orig/123748539.png" width="50" height="50"/>
                      <a href="#"></td>
                       <td> <i class="fa fa-pencil-square-o fa-lg"></i></td>
              </tr>
            </tbody>
          </table>
</div><!--column-->
</div><!--row-->
</div> <!--panelbody-->
</div> <!--paneldefault-->
</div><!--column-->
</div><!--row-->


 
   

app/views/pages/gatowers.html.erb
<div class="container-fluid">
      <div class="row">
        <div class="col-md-2 sidebar">
          <div class="row placeholders">
          <img src="http://www.ccareynkf.com/FileStore/IMG/Agt_59B4875E12004ED397A4A176FE35AD46.jpg" width="130" height="130" class="img-circle"/>
            <h4>Jason Forcier</h4>
              <span class="text-muted">Cornish & Carey</span>
            </div>
          <%= render 'layouts/navbarside' %>
          </div><!--column-->
        </div><!--row-->
      </div><!--container-->
<!-- Sidebar Nav -->
<!-- Dashboard Header -->
<div class="row">
        <div class="col-md-10 col-md-offset-2">
          <h2 class="page-header"><p><i class="fa fa-folder-open fa-2x"></i> Current Deals - Listing</p>
          <div class="btn-group">
            <button type="button" class="btn btn-u btn-u-green">Listings</button>
            <button type="button" class="btn btn-u btn-u-green dropdown-toggle" data-toggle="dropdown">
              <span class="caret"></span>
              <span class="sr-only">Toggle Dropdown</span>
            </button>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "Procuring", current_deals_path %></li>
            </ul>
        </div></h2>
        </div>
      </div>
 <div class="row">
        <div class="col-md-10 col-md-offset-2">
          <ul class="nav nav-tabs">
      <li><%= link_to 'Cupertino City Center', ccc_path %></li>
      <li><%= link_to 'Santa Clara Office Center', scc_path %></li>
      <li class="active"><%= link_to 'Great America Towers', gatowers_path %></li>
      <li><button type="button" class="btn btn-u btn-u-green"><i class="fa fa-plus-square fa-fw"></i>Add Listing</button>
    </ul></li>
        </div><!--column-->
  		</div><!--row-->


<div class="row top-buffer">
  <div class="col-md-10 col-md-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Overview</h3>
      </div><!--panelheading-->
      <div class="panel-body">
        <div class="row">
          <div class="col-md-12">
            <button type="button" class="btn btn-u btn-u-green"><i class="fa fa-camera fa-fw"></i>Create Report</button>
        </div>
      </div>
        <div class="row top-buffer">
          <div class="col-md-12">
				<table class="table table-hover">
					<thead>
						<tr>
							<th>Partner (If Any)</th>
							<th>Landlord</th>
							<th>Contact</th>
							<th>Building Size</th>
							<th>Vacancy</th>
							<th>Asking Rate</th>
							<th>Opex</th>
							<th></th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>Todd Shaffer</td>
							<td>Prometheus</td>
							<td>John Doe</td>
							<td>100,000sf</td>
							<td>20%</td>
							<td>$5.50NNN</td>
							<td>$1.00</td>
							<td><i class="fa fa-pencil-square-o fa-lg"></i></td>
						</tr>
					</tbody>
				</table>
				</div><!--column-->
			</div><!--row-->
			</div><!--panelbody-->
		</div><!--paneldefault-->
	</div><!--column-->
</div><!--row-->

<div class="row">
  <div class="col-md-10 col-md-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Active Deals</h3>
      </div><!--panelheading-->
      <div class="panel-body">
        <div class="row">
          <div class="col-md-12">
            <button type="button" class="btn btn-u btn-u-green"><i class="fa fa-plus-square fa-fw"></i>Add Deal</button>
        </div>
      </div>
        <div class="row top-buffer">
          <div class="col-md-12">
				<table class="table table-hover">
					<thead>
						<tr>
							<th>Tenant</th>
							<th>Broker/Agent</th>
							<th>Suite #</th>
							<th>Size (SF)</th>
							<th>Deal Stage</th>
							<th>Comments/Notes</th>
							<th>Documents</th>
							<th></th>
						</tr>
					</thead>
					<tbody>

						<tr>
							<td>Mozilla, Inc</td>
							<td>Jeff Arrillaga</td>
							<td># 250</td>
							<td>30,000SF</td>
							<td>Second round of proposals</td>
							<td>Reviewing counter proposal </td>
							<td><a href="#">
									<img src="http://img.docstoccdn.com/thumb/orig/123748539.png" width="50" height="50"/>
				            <a href="#">
				            <img src="http://www.execsuitescheyenne.com/public/Floorplan_mezz.jpg" width="50" height="50"/></td></td>
							<td><i class="fa fa-pencil-square-o fa-lg"></i></td>
						</tr>
						<tr>
							<td>Pure Storage, Inc.</td>
							<td>Jeff Rogers</td>
							<td>#400</td>
							<td>9,000sf</td>
							<td>Lease negotiations</td>
							<td>Lease drafted. Sent for review</td>
							<td><a href="#">
									<img src="http://img.docstoccdn.com/thumb/orig/123748539.png" width="50" height="50"/>
				            <a href="#">
				            <img src="http://www.execsuitescheyenne.com/public/Floorplan_mezz.jpg" width="50" height="50"/></td></td>
							<td><i class="fa fa-pencil-square-o fa-lg"></i></td>
						</tr>
					</tbody>
				</table>
				</div><!--column-->
			</div><!--row-->
			</div><!--panelbody-->
		</div><!--paneldefault-->
	</div><!--column-->
</div><!--row-->

<div class="row">
  <div class="col-md-10 col-md-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Touring Activity</h3>
      </div><!--panelheading-->
      <div class="panel-body">
        <div class="row">
          <div class="col-md-12">
            <button type="button" class="btn btn-u btn-u-green"><i class="fa fa-plus-square fa-fw"></i>Add Prospect</button>
        </div>
      </div>
        <div class="row top-buffer">
          <div class="col-md-12">
<table class="table table-hover">
	<thead>
		<tr>
			<th>Tenant</th>
			<th>Broker/Agent</th>
			<th>Requirement</th>
			<th>Timing</th>
			<th>Tour (y/n)</th>
			<th>Tour Date</th>
			<th>Comments/Notes</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<p><h3><strong> Touring Activity </strong></h3></p>

		<tr>
			<td>N/A</td>
			<td>Jason Forcier - Cornish & Carey </td>
			<td>4,000-6,000sf, 3 Conf Rooms and 1 Private</td>
			<td>Q'2 - 2014</td>
			<td>Yes</td>
			<td> 1/15/2014 </td>
			<td>Preliminary Interest</td>
			<td> <i class="fa fa-pencil-square-o fa-lg"></i><i class="fa fa-trash-o fa-lg"></i></td>
		</tr>
		<tr>
			<td>ABC, Inc.</td>
			<td>Mike Connor - CTBT </td>
			<td>10,000-15,000sf, Law firm buildout</td>
			<td>Q'4 - 2014</td>
			<td>Yes</td>
			<td> 1/24/2014 </td>
			<td>Liked suite 400. Expecting proposal from Broker soon.</td>
			<td> <i class="fa fa-pencil-square-o fa-lg"></i><i class="fa fa-trash-o fa-lg"></i></td>
		</tr>
		<tr>
			<td>XYZ, Inc.</td>
			<td>Rich Branning - JLL </td>
			<td>20,000-35,000sf, Tech office layout. Large server room needed</td>
			<td>Q'2 - 2015</td>
			<td>No</td>
			<td> N/A </td>
			<td>Setting up tour for next week</td>
			<td> <i class="fa fa-pencil-square-o fa-lg"></i><i class="fa fa-trash-o fa-lg"></i></td>
		</tr>
	</tbody>
</table>
		</div><!--column-->
			</div><!--row-->
			</div><!--panelbody-->
		</div><!--paneldefault-->
	</div><!--column-->
</div><!--row-->