config/routes.rb
Realestateapp::Application.routes.draw do
  devise_for :users
  resources :scomps

  resources :comps

  resources :slistings

  resources :listings

  root "pages#home"
  get "about" => "pages#about"
  get "my_profile" => "pages#my_profile"
  get "search_database" => "pages#search_database"
    get "for_lease" => "pages#for_lease"
    get "lease_comps" => "pages#lease_comps"
    get "for_sale" => "pages#for_sale"
    get "sale_comps" => "pages#sale_comps"
    get "property_directory" => "pages#property_directory"
  get "my_listings" => "pages#my_listings"
  get "current_deals" => "pages#current_deals"
  get "closed_deals" => "pages#closed_deals"
  get "accounts_receivable" => "pages#accounts_receivable"
  get "tenant_rep" => "pages#tenant_rep"
  get "landlord_rep" => "pages#landlord_rep"
  get "bitcasa" => "pages#bitcasa"
  get "gameclosure" => "pages#gameclosure"
  get "startx" => "pages#startx"
  get "ccc" => "pages#ccc"
  get "scc" => "pages#scc"
  get "gatowers" => "pages#gatowers"
  get "recently_closed" => "pages#recently_closed"
  get "upcoming_exp" => "pages#upcoming_exp"
  get "create_invoice" => "pages#create_invoice"
  get "commissions" => "pages#commissions"
  get "local" => "pages#local"
  get "national" => "pages#national"
  get "regional" => "pages#regional"
  get "international" => "pages#international"
  get "dashboard" => "pages#dashboard"
  get "pipeline" => "pages#pipeline"
  get "detail" => "pages#detail"
  get "manager_admin" => "pages#manager_admin"
  get "detail_comp" => "pages#detail_comp"
  get "new_listings" => "pages#new_listings"
  get "new_comps" => "pages#new_comps"
  resources :users

  

end

app/views/layouts/_closed.html.erb
<ul class="nav nav-pills">
		<li><%= link_to 'Recently Closed', recently_closed_path %></li>
		<li><%= link_to 'Upcoming Expirations', upcoming_exp_path %></li>
	</ul>

app/views/layouts/_dbsearch.html.erb
	<ul class="nav nav-pills">
		<li><%= link_to "For Lease", "for_lease"%></li>
		<li><%= link_to "Lease Comps", "lease_comps"%></li>
		<li><%= link_to "For Sale", "for_sale"%></li>
		<li><%= link_to "Sale Comps", "sale_comps"%></li>
		<li><%= link_to "Property Directory", "property_directory"%></li>
	</ul>

app/views/layouts/_deals.html.erb
<ul class="nav nav-pills">
		<li><%= link_to 'Active', tenant_rep_path %></li>
		<li><%= link_to 'Prelimnary', landlord_rep_path %></li>
	</ul>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#"><i class="fa fa-cloud fa-lg fa-fw"></i>dataCRE</a>
  </div>


  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-building-o fa-lg fa-fw"></i>Create Data <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><%= link_to for_lease_path do %>
        <i class="fa fa-search fa-lg fa-fw"></i>Search Database
        <% end %>
      </li>
          <li><%= link_to new_listing_path do %>
          <i class="fa fa-plus-circle fa-lg fa-fw"></i>Lease Listing
          <% end %>
        </li>
        <li><%= link_to new_slisting_path do %>
          <i class="fa fa-plus-circle fa-lg fa-fw"></i>Sale Listing
          <% end %>
        </li>
        <li><%= link_to new_comp_path do %>
          <i class="fa fa-plus-circle fa-lg fa-fw"></i>Lease Comp
          <% end %>
        </li>
        <li><%= link_to new_scomp_path do %>
          <i class="fa fa-plus-circle fa-lg fa-fw"></i>Sale Comp
          <% end %>
        </li>
        </ul>
      </li>
        <li><%= link_to edit_user_registration_path do %>
          <i class="fa fa-cog fa-lg fa-fw"></i>Settings
          <% end %></li>
        <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
        <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Sign In", new_user_session_path %></li>
        <% end %> 
        
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/_nav.html.erb
<ul class="nav nav-tabs">
  <li class="active">
    <li><%= link_to "My Profile", my_profile_path %></li>
  </li>
  <li><%= link_to "Search Database", for_lease_path %></li>
  <li><%= link_to "My Listings", my_listings_path %></li>
  <li><%= link_to "Current Deals", current_deals_path %></li>
  <li><%= link_to "Closed Deals", closed_deals_path %></li>
  <li><%= link_to "Accounts Receivable", accounts_receivable_path %></li>
</ul>

app/views/layouts/_navbarside.html.erb
<ul class="nav nav-stacked">
            <li><%= link_to for_lease_path do %>
                  <i class="fa fa-search fa-lg fa-fw"></i> Search Database
                  <% end %></li>
            <li><%= link_to dashboard_path do %>
                  <i class="fa fa-tachometer fa-lg fa-fw"></i>Dashboard
                  <% end %></li>
            <li><%= link_to my_listings_path do %>
                  <i class="fa fa-building-o fa-lg fa-fw"></i>My Listings
                  <% end %></li>
            <li></i><%= link_to current_deals_path do %>
            <i class="fa fa-folder-open fa-lg fa-fw"></i>Current Deals
                  <% end %> </li>
            <li><%= link_to new_listings_path do %>
            <i class="fa fa-flag fa-lg fa-fw"></i> New Listings
                  <% end %></li>
            <li><%= link_to new_comps_path do %>
            <i class="fa fa-flag-checkered fa-lg fa-fw"></i> New Comps
                  <% end %></li>
            <li><%= link_to closed_deals_path do %>
                  <i class="fa fa-archive fa-lg fa-fw"></i>Transaction History
                  <% end %></li>
            <li><%= link_to accounts_receivable_path do %>
                  <i class="fa fa-usd fa-lg fa-fw"></i>Accounts Due
                  <% end %></li>
          </ul>

app/views/layouts/_top.html.erb
<!--=== Top ===-->    
<div class="top">
    <div class="container">         
        <ul class="loginbar pull-right">
            
            <li class="devider"></li>   
            <li><a href="page_faq.html">Help</a></li>  
            <li class="devider"></li>   
            <li><a href="page_login.html">Login</a></li>   
        </ul>
    </div>      
</div><!--/top-->
<!--=== End Top ===-->  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SuiteCloud</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <link rel="stylesheet" href="http://cdn.oesmith.co.uk/morris-0.4.3.min.css">
 <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
 <script src="//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
 <script src="http://cdn.oesmith.co.uk/morris-0.4.3.min.js"></script>
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-info") %>
    <% end %>
<%= yield %>
</div>

</body>
</html>